[package]
name = "securust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.1", features = ["derive"] }
iced = "0.12.1"
orion = "0.17.6"
pad = "0.1.6"
